name: Release

on:
  release:
    types: [published]

jobs:
  deploy_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_API_USER }}
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: ${{ secrets.PYPI_REPO_URL }}
